### ISSUE TITLE
`dep ensure` failing locally

### ISSUE THREAD

**Issue by asafpelegcodes** [armory-io/terraform-provider-spinnaker#19]
I'm following the instructions on https://github.com/armory-io/terraform-provider-spinnaker#build-from-source 

When I execute `dep ensure` I get the following error
grouped write of manifest, lock and vendor: failed to export github.com/spinnaker/spin: fatal: failed to unpack tree object dc900bc5b869e8d563bae25faf14826174576b2b

Running MacOS 10.14.4
go version go1.12.1 darwin/amd64

go env below
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/[myuser]/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/[myuser]/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/g4/3hkswdsn3sq3ty9hmgnmlxsr0000gp/T/go-build946451482=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by ethanfrogers** [comment]
Sorry for the delay here. Since this issue was filed we've moved to Go modules. I'm going to close this since it's no longer an issue!
