### ISSUE TITLE
Spinnaker application name cannot use dash (-) anymore

### ISSUE THREAD

**Issue by kserrano4cast** [armory-io/terraform-provider-spinnaker#40]
After PR #37, it is not possible to use `-` in application names.
However, this is perfectly allowed by Spinnaker, both from the UI and the CLI.
They even use `my-app` as an example in their official documentation 
https://www.spinnaker.io/guides/spin/app/#create-a-new-application-using-save

The validation should accept all valid names, and not restrict to only alpha numerical characters.

**Comment by awsiv** [comment]
Ok spinnaker actually has different naming restrictions based on cloud providers:


```
'appengine' : new NameConstraint(58, '^[a-z0-9]*$'),
    'aws'       : new NameConstraint(250, '^[a-zA-Z_0-9.]*$'),
    'dcos'      : new NameConstraint(127, '^[a-z0-9]*$'),
    'gce'       : new NameConstraint(63, '^([a-zA-Z][a-zA-Z0-9]*)?$'),
    'kubernetes': new NameConstraint(63, '^([a-zA-Z][a-zA-Z0-9-]*)$'),
    'openstack' : new NameConstraint(250, '^[a-zA-Z_0-9.]*$'),
    'titus'     : new NameConstraint(250, '^[a-zA-Z_0-9.]*$')
```
https://github.com/spinnaker/orca/blob/master/orca-applications/src/main/groovy/com/netflix/spinnaker/orca/applications/utils/ApplicationNameValidator.groovy#L26-L34

Need to have different validators based on the specified provider

**Comment by ethanfrogers** [comment]
When creating an application via the UI it is possible for application names to contain a `-`. I think removing this restriction from this provider makes sense, especially since applications are no longer required to be coupled to a specific cloud provider.

**Comment by yogeek** [comment]
Hi @ethanfrogers 

Is it possible to reopen this issue please ?

I have the followinf behaviour :

- in the UI, forbidden to add an application (AWS) with a dash
![image](https://user-images.githubusercontent.com/9500406/80014048-0e86ca00-84d0-11ea-8476-a51740e2ae7e.png)

- with the terraform provider, no error when adding such an application but then impossible to execute a pipeline in this application. This message is displayed:
```
Exception ( Monitor Deploy ) (Use alphanumeric characters only)
```

So I am not sure removing this restriction makes sense...
