### ISSUE TITLE
Setup the Api-Key to use in custom header

### ISSUE THREAD

**Issue by wesleywilian** [armory-io/terraform-provider-spinnaker#46]
Hello,
I'm with problems using the provider.

On plan command we have the following message error
```
Error: invalid character '<' looking for beginning of value

  on create_pipeline.tf line 1, in provider "spinnaker":
   1: provider "spinnaker" {
```

After some investigation, seems our api is returning html instead json code. Maybe because of absence of authentication in the terraform request.

I found this PR #23 ( by @MarkFreebairn ), that allow we to use some Api-Key as showed in the README.

How can we configure this Api-Key in spinnaker ?

I didn't find it in the documentation

Thanks

**Comment by wesleywilian** [comment]
Solved using the header as
`default_headers    = "Authorization=Basic XXXXXXXXXX=="
`
Thanks

**Comment by esn89** [comment]
Hi, I'm getting a similar error when I use this:

```
Error: Error running plan: 1 error occurred:
	* provider.spinnaker: invalid character '<' looking for beginning of value
```

What exactly did you change and where, could you please show me?

**Comment by wesleywilian** [comment]
Hello @esn89 
You have to use a header on API of the spinnaker.
`default_headers = "Authorization=Basic XXXXXXXXXX=="`

https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Headers/Authorization

You can use a credential, as follows:
aladdin:opensesame > encoded in base64 > YWxhZGRpbjpvcGVuc2VzYW1l

`default_headers = "Authorization=Basic YWxhZGRpbjpvcGVuc2VzYW1l"`

**Comment by esn89** [comment]
Is this something I change on the server side of the spinnaker gate?

Or the way I authenticate to it?

**Comment by wesleywilian** [comment]
It's way you authenticate

You can use something like this

```
provider "spinnaker" {
    server = "https://spinnaker-gate-url"
    ignore_cert_errors = true
    default_headers    = "Authorization=Basic YWxhZGRpbjpvcGVuc2VzYW1l"
}
```

**Comment by esn89** [comment]
Thanks.   And the value of the `default_headers` is simply an API key in base64?

**Comment by wesleywilian** [comment]
The `default_headers` is the http header authorization. It's not an api key, it is simply a common username and password encoded in base64 on `Authorization` header.
