### ISSUE TITLE
Willing to contribute; Need a license

### ISSUE THREAD

**Issue by joshuarowe-salesforce** [armory-io/terraform-provider-spinnaker#5]
My company is willing to contribute to this project, but the project needs a license.  Thank you!

**Comment by ethanfrogers** [comment]
Thanks for the heads up @joshuarowe-salesforce! Let me look into this!

**Comment by joshuarowe-salesforce** [comment]
I do have a contribution to make already.  When this project is updated with license information, I'll be able to conclude my company's legal process and I'll happily post the PR.  Thanks!

**Comment by ethanfrogers** [comment]
@joshuarowe-salesforce sorry for the delay! I've gone ahead and added an MIT license. I look forward to your contribution!
