### ISSUE TITLE
project status

### ISSUE THREAD

**Issue by wyardley** [armory-io/terraform-provider-spinnaker#52]
Hi - I had a few questions about project status:

1) Is this a project that Armory is working on actively still? Is the fork at https://github.com/dmyerscough/terraform-provider-spinnaker related directly? It seems like @dmyerscough has proposed some PRs here, but that fork also has some drift from here in both directions now.

2) The fork above has some releases, but this project does not yet; are tagged releases planned?

3) Are either of the projects moving towards trying to move into the official terraform provider registry? Currently, using the project in CI, or using frameworks like Atlantis, is a bit of a headache because it has to be downloaded separately.

**Comment by KeisukeYamashita** [comment]
@wyardley FYI: Hi, I am also developing a provider too. If you are interested, PTAL.

https://github.com/mercari/terraform-provider-spinnaker/tree/master/spinnaker

**Comment by dmyerscough** [comment]
@wyardley I haven't used this plugin in a while. @KeisukeYamashita can you register your plugin with HashiCorp so people will see your plugin over this one?

**Comment by KeisukeYamashita** [comment]
@dmyerscough  Yeah, sure. I've applied to Hashicorp and now I'm waiting for their response. In the meantime, you have to install from the GitHub release 🙇

**Comment by wyardley** [comment]
btw, 0.13 has some good new options around decentralized registries / providers, though it still doesn't support direct from GH installation. I was able to trick it into installing @dmyerscough's by downloading the binary into the expected location.

https://www.terraform.io/docs/configuration/providers.html
https://www.terraform.io/docs/commands/cli-config.html#provider-installation

**Comment by stevenaldinger** [comment]
I had a convo with armory recently and they are no longer maintaining this repo. They're working on a proprietary abstraction that replaces pipeline templates instead.

**Comment by KeisukeYamashita** [comment]
@wyardley @stevenaldinger Sorry for the late reply. Today, we finally published our provider! Please take a look 🎉 
https://registry.terraform.io/providers/mercari/spinnaker/latest
